/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class ChatRecord extends org.jooq.impl.UpdatableRecordImpl<com.cahoots.jooq.tables.records.ChatRecord> {

	private static final long serialVersionUID = 855950659;

	/**
	 * The table column <code>public.chat.from</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__from_fk
	 * FOREIGN KEY (from)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public void setFrom(java.lang.String value) {
		setValue(com.cahoots.jooq.tables.Chat.CHAT.FROM, value);
	}

	/**
	 * The table column <code>public.chat.from</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__from_fk
	 * FOREIGN KEY (from)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public java.lang.String getFrom() {
		return getValue(com.cahoots.jooq.tables.Chat.CHAT.FROM);
	}

	/**
	 * Link this record to a given {@link com.cahoots.jooq.tables.records.UsersRecord 
	 * UsersRecord}
	 */
	public void setFrom(com.cahoots.jooq.tables.records.UsersRecord value) {
		if (value == null) {
			setValue(com.cahoots.jooq.tables.Chat.CHAT.FROM, null);
		}
		else {
			setValue(com.cahoots.jooq.tables.Chat.CHAT.FROM, value.getValue(com.cahoots.jooq.tables.Users.USERS.USERNAME));
		}
	}

	/**
	 * The table column <code>public.chat.from</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__from_fk
	 * FOREIGN KEY (from)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public com.cahoots.jooq.tables.records.UsersRecord fetchUsersByFrom() {
		return create()
			.selectFrom(com.cahoots.jooq.tables.Users.USERS)
			.where(com.cahoots.jooq.tables.Users.USERS.USERNAME.equal(getValue(com.cahoots.jooq.tables.Chat.CHAT.FROM)))
			.fetchOne();
	}

	/**
	 * The table column <code>public.chat.to</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__to_fk
	 * FOREIGN KEY (to)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public void setTo(java.lang.String value) {
		setValue(com.cahoots.jooq.tables.Chat.CHAT.TO, value);
	}

	/**
	 * The table column <code>public.chat.to</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__to_fk
	 * FOREIGN KEY (to)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public java.lang.String getTo() {
		return getValue(com.cahoots.jooq.tables.Chat.CHAT.TO);
	}

	/**
	 * Link this record to a given {@link com.cahoots.jooq.tables.records.UsersRecord 
	 * UsersRecord}
	 */
	public void setTo(com.cahoots.jooq.tables.records.UsersRecord value) {
		if (value == null) {
			setValue(com.cahoots.jooq.tables.Chat.CHAT.TO, null);
		}
		else {
			setValue(com.cahoots.jooq.tables.Chat.CHAT.TO, value.getValue(com.cahoots.jooq.tables.Users.USERS.USERNAME));
		}
	}

	/**
	 * The table column <code>public.chat.to</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__to_fk
	 * FOREIGN KEY (to)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public com.cahoots.jooq.tables.records.UsersRecord fetchUsersByTo() {
		return create()
			.selectFrom(com.cahoots.jooq.tables.Users.USERS)
			.where(com.cahoots.jooq.tables.Users.USERS.USERNAME.equal(getValue(com.cahoots.jooq.tables.Chat.CHAT.TO)))
			.fetchOne();
	}

	/**
	 * The table column <code>public.chat.message</code>
	 */
	public void setMessage(java.lang.String value) {
		setValue(com.cahoots.jooq.tables.Chat.CHAT.MESSAGE, value);
	}

	/**
	 * The table column <code>public.chat.message</code>
	 */
	public java.lang.String getMessage() {
		return getValue(com.cahoots.jooq.tables.Chat.CHAT.MESSAGE);
	}

	/**
	 * The table column <code>public.chat.date</code>
	 */
	public void setDate(java.sql.Time value) {
		setValue(com.cahoots.jooq.tables.Chat.CHAT.DATE, value);
	}

	/**
	 * The table column <code>public.chat.date</code>
	 */
	public java.sql.Time getDate() {
		return getValue(com.cahoots.jooq.tables.Chat.CHAT.DATE);
	}

	/**
	 * The table column <code>public.chat.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(com.cahoots.jooq.tables.Chat.CHAT.ID, value);
	}

	/**
	 * The table column <code>public.chat.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(com.cahoots.jooq.tables.Chat.CHAT.ID);
	}

	/**
	 * Create a detached ChatRecord
	 */
	public ChatRecord() {
		super(com.cahoots.jooq.tables.Chat.CHAT);
	}
}
