/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class DatabaseVersionRecord extends org.jooq.impl.TableRecordImpl<com.cahoots.jooq.tables.records.DatabaseVersionRecord> {

	private static final long serialVersionUID = -1716658668;

	/**
	 * The table column <code>public.database_version.version</code>
	 */
	public void setVersion(java.lang.Integer value) {
		setValue(com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION.VERSION, value);
	}

	/**
	 * The table column <code>public.database_version.version</code>
	 */
	public java.lang.Integer getVersion() {
		return getValue(com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION.VERSION);
	}

	/**
	 * Create a detached DatabaseVersionRecord
	 */
	public DatabaseVersionRecord() {
		super(com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION);
	}
}
