/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 392355856;

	/**
	 * The singleton instance of public
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.cahoots.jooq.Sequences.CHAT_ID_SEQ,
			com.cahoots.jooq.Sequences.ROLES_ID_SEQ,
			com.cahoots.jooq.Sequences.USERS_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.cahoots.jooq.tables.Chat.CHAT,
			com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION,
			com.cahoots.jooq.tables.Roles.ROLES,
			com.cahoots.jooq.tables.Users.USERS);
	}
}
