/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public final class Sequences {

	/**
	 * The sequence public.roles_id_seq
	 */
	public static final org.jooq.Sequence<java.lang.Long> ROLES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("roles_id_seq", com.cahoots.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence public.users_id_seq
	 */
	public static final org.jooq.Sequence<java.lang.Long> USERS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("users_id_seq", com.cahoots.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * No instances
	 */
	private Sequences() {}
}
