/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table public.chat
	 */
	public static final com.cahoots.jooq.tables.Chat CHAT = com.cahoots.jooq.tables.Chat.CHAT;

	/**
	 * The table public.database_version
	 */
	public static final com.cahoots.jooq.tables.DatabaseVersion DATABASE_VERSION = com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION;

	/**
	 * The table public.roles
	 */
	public static final com.cahoots.jooq.tables.Roles ROLES = com.cahoots.jooq.tables.Roles.ROLES;

	/**
	 * The table public.users
	 */
	public static final com.cahoots.jooq.tables.Users USERS = com.cahoots.jooq.tables.Users.USERS;

	/**
	 * No instances
	 */
	private Tables() {}
}
