/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Chat extends org.jooq.impl.UpdatableTableImpl<com.cahoots.jooq.tables.records.ChatRecord> {

	private static final long serialVersionUID = 1963648798;

	/**
	 * The singleton instance of public.chat
	 */
	public static final com.cahoots.jooq.tables.Chat CHAT = new com.cahoots.jooq.tables.Chat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cahoots.jooq.tables.records.ChatRecord> getRecordType() {
		return com.cahoots.jooq.tables.records.ChatRecord.class;
	}

	/**
	 * The table column <code>public.chat.from</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__from_fk
	 * FOREIGN KEY (from)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.ChatRecord, java.lang.String> FROM = createField("from", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.chat.to</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT chat__to_fk
	 * FOREIGN KEY (to)
	 * REFERENCES public.users (username)
	 * </pre></code>
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.ChatRecord, java.lang.String> TO = createField("to", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.chat.message</code>
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.ChatRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The table column <code>public.chat.date</code>
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.ChatRecord, java.sql.Time> DATE = createField("date", org.jooq.impl.SQLDataType.TIME, this);

	/**
	 * The table column <code>public.chat.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.ChatRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	public Chat() {
		super("chat", com.cahoots.jooq.Public.PUBLIC);
	}

	public Chat(java.lang.String alias) {
		super(alias, com.cahoots.jooq.Public.PUBLIC, com.cahoots.jooq.tables.Chat.CHAT);
	}

	@Override
	public org.jooq.Identity<com.cahoots.jooq.tables.records.ChatRecord, java.lang.Integer> getIdentity() {
		return com.cahoots.jooq.Keys.IDENTITY_CHAT;
	}

	@Override
	public org.jooq.UniqueKey<com.cahoots.jooq.tables.records.ChatRecord> getMainKey() {
		return com.cahoots.jooq.Keys.CHAT_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<com.cahoots.jooq.tables.records.ChatRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.cahoots.jooq.tables.records.ChatRecord>>asList(com.cahoots.jooq.Keys.CHAT_PKEY, com.cahoots.jooq.Keys.U_ID);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<com.cahoots.jooq.tables.records.ChatRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.cahoots.jooq.tables.records.ChatRecord, ?>>asList(com.cahoots.jooq.Keys.CHAT__FROM_FK, com.cahoots.jooq.Keys.CHAT__TO_FK);
	}

	@Override
	public com.cahoots.jooq.tables.Chat as(java.lang.String alias) {
		return new com.cahoots.jooq.tables.Chat(alias);
	}
}
