/**
 * This class is generated by jOOQ
 */
package com.cahoots.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class DatabaseVersion extends org.jooq.impl.TableImpl<com.cahoots.jooq.tables.records.DatabaseVersionRecord> {

	private static final long serialVersionUID = 1643467867;

	/**
	 * The singleton instance of public.database_version
	 */
	public static final com.cahoots.jooq.tables.DatabaseVersion DATABASE_VERSION = new com.cahoots.jooq.tables.DatabaseVersion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.cahoots.jooq.tables.records.DatabaseVersionRecord> getRecordType() {
		return com.cahoots.jooq.tables.records.DatabaseVersionRecord.class;
	}

	/**
	 * The table column <code>public.database_version.version</code>
	 */
	public final org.jooq.TableField<com.cahoots.jooq.tables.records.DatabaseVersionRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this);

	public DatabaseVersion() {
		super("database_version", com.cahoots.jooq.Public.PUBLIC);
	}

	public DatabaseVersion(java.lang.String alias) {
		super(alias, com.cahoots.jooq.Public.PUBLIC, com.cahoots.jooq.tables.DatabaseVersion.DATABASE_VERSION);
	}

	@Override
	public com.cahoots.jooq.tables.DatabaseVersion as(java.lang.String alias) {
		return new com.cahoots.jooq.tables.DatabaseVersion(alias);
	}
}
